apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sprint-tls-cert
  namespace: prod
spec:
  secretName: sprint-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - sprint.suitestudy.com
