apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prefect-stg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Team-Neki/Team-Neki-GitOps.git
    targetRevision: main
    path: overlays/prefect-stg
  destination:
    server: https://kubernetes.default.svc
    namespace: prefect-stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
