apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yapp-monitoring-tls-cert
  namespace: prod
spec:
  secretName: yapp-monitoring-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - yapp-monitoring.suitestudy.com
